<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!--[if mso]>
    <xml>
        <w:WordDocument xmlns:w="urn:schemas-microsoft-com:office:word">
            <w:DontUseAdvancedTypographyReadingMail/>
        </w:WordDocument>
        <o:OfficeDocumentSettings>
            <o:PixelsPerInch>96</o:PixelsPerInch>
            <o:AllowPNG/>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]--><!--[if !mso]><!-->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@100;200;300;400;500;600;700;800;900"
          rel="stylesheet" type="text/css"><!--<![endif]-->
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            padding: 0;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: inherit !important;
        }

        #MessageViewBody a {
            color: inherit;
            text-decoration: none;
        }

        p {
            line-height: inherit
        }

        .desktop_hide,
        .desktop_hide table {
            mso-hide: all;
            display: none;
            max-height: 0px;
            overflow: hidden;
        }

        .image_block img+div {
            display: none;
        }

        sup,
        sub {
            font-size: 75%;
            line-height: 0;
        }

        @media (max-width:620px) {

            .desktop_hide table.icons-inner,
            .row-12 .column-1 .block-5.social_block .alignment table,
            .social_block.desktop_hide .social-table {
                display: inline-block !important;
            }

            .icons-inner {
                text-align: center;
            }

            .icons-inner td {
                margin: 0 auto;
            }

            .mobile_hide {
                display: none;
            }

            .row-content {
                width: 100% !important;
            }

            .stack .column {
                width: 100%;
                display: block;
            }

            .mobile_hide {
                min-height: 0;
                max-height: 0;
                max-width: 0;
                overflow: hidden;
                font-size: 0px;
            }

            .desktop_hide,
            .desktop_hide table {
                display: table !important;
                max-height: none !important;
            }

            .row-1 .column-1 .block-4.paragraph_block td.pad {
                padding: 10px 30px 20px !important;
            }

            .row-12 .column-1 .block-2.paragraph_block td.pad>div,
            .row-12 .column-1 .block-5.social_block .alignment,
            .row-12 .column-1 .block-6.paragraph_block td.pad>div,
            .row-12 .column-1 .block-7.paragraph_block td.pad>div {
                text-align: center !important;
            }
        }
    </style>
    <!--[if mso ]>
    <style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style>
    <![endif]-->
</head>

<body class="body"
      style="background-color: #000000; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">
<table border="0" cellpadding="0" cellspacing="0" class="nl-container" role="presentation"
       style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000;"
       width="100%">
    <tbody>
    <tr>
        <td>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-1" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-image: url('https://i.imgur.com/k0fT1cEg.jpg'); background-repeat: no-repeat; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-top:25px;width:100%;padding-right:0px;padding-left:0px;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 60px;"><a href="https://www.example.com"
                                                                                     target="_blank"><img
                                                            alt="Your logo"
                                                            height="auto"
                                                            src="https://d0d3920d1a.imgdist.com/pub/bfra/33gcmoa0/k4h/3bt/lud/1200px-WoW_icon.svg.png"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Your logo" width="60"></a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:35px;">
                                                <div style="color:#ff821c;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:400;letter-spacing:16px;line-height:1.2;text-align:center;mso-line-height-alt:19px;">
                                                    &nbsp;
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="10" cellspacing="0" class="heading_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <h1 style="margin: 0; color: #ffffff; direction: ltr; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 38px; font-weight: 500; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 46px;">
                                                    BIENVENIDO A LA COMUNIDAD</h1>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-4"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:20px;padding-left:60px;padding-right:60px;padding-top:10px;">
                                                <div style="color:#ffffff;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.5;text-align:center;mso-line-height-alt:24px;">
                                                    <p style="margin: 0;">Confirma tu correo electrónico y desbloquea
                                                        toda la diversión.</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="button_block block-5"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:25px;padding-left:10px;padding-right:10px;padding-top:10px;text-align:center;">
                                                <div align="center" class="alignment"><a href="${url}"
                                                                                         style="color:#ffffff;text-decoration:none;"
                                                                                         target="_blank">
                                                    <!--[if mso]>
                                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                                 href="${url}"
                                                                 style="height:52px;width:182px;v-text-anchor:middle;"
                                                                 arcsize="0%" fillcolor="#ff821c">
                                                        <v:stroke dashstyle="Solid" weight="0px" color="#ff821c"/>
                                                        <w:anchorlock/>
                                                        <v:textbox inset="0px,0px,0px,0px">
                                                            <center dir="false"
                                                                    style="color:#ffffff;font-family:sans-serif;font-size:16px">
                                                    <![endif]--><span class="button"
                                                                      style="background-color: #ff821c; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 0px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 10px; padding-top: 10px; padding-left: 30px; padding-right: 30px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span
                                                        style="word-break: break-word; line-height: 32px;">CONFIRMAR CORREO</span></span>
                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-6"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 600px;"><img
                                                            alt="Odam4"
                                                            height="auto"
                                                            src="https://i.pinimg.com/originals/dd/ea/d1/ddead1b17ab10503d5865a9977ebdb0a.jpg"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Odam4" width="600"></div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-2" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-3" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: middle;"
                                    width="41.666666666666664%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="heading_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:center;width:100%;">
                                                <h2 style="margin: 0; color: #ffffff; direction: ltr; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 30px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: left; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;">
                                                    <span class="tinyMce-placeholder"
                                                          style="word-break: break-word;"><span
                                                            style="word-break: break-word; color: #ff821c;"><span
                                                            style="word-break: break-word; color: #ffffff;">Impulsa el servidor y</span> desbloquea contenido épico</span></span>
                                                </h2>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:10px;">
                                                <div style="color:#ffffff;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:300;letter-spacing:0px;line-height:1.5;text-align:left;mso-line-height-alt:24px;">
                                                    <p style="margin: 0;">Apoya al servidor y consigue contenido
                                                        exclusivo, productos únicos y monturas de colección.</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="button_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:25px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:left;">
                                                <div align="left" class="alignment"><a href="https://www.example.com"
                                                                                       style="color:#ffffff;text-decoration:none;"
                                                                                       target="_blank">
                                                    <!--[if mso]>
                                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                                 href="https://www.example.com"
                                                                 style="height:52px;width:101px;v-text-anchor:middle;"
                                                                 arcsize="0%" fillcolor="#ff821c">
                                                        <v:stroke dashstyle="Solid" weight="0px" color="#ff821c"/>
                                                        <w:anchorlock/>
                                                        <v:textbox inset="0px,0px,0px,0px">
                                                            <center dir="false"
                                                                    style="color:#ffffff;font-family:sans-serif;font-size:16px">
                                                    <![endif]--><span class="button"
                                                                      style="background-color: #ff821c; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 0px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 10px; padding-top: 10px; padding-left: 30px; padding-right: 30px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span
                                                        style="word-break: break-word; line-height: 32px;">DONAR</span></span>
                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-2"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: middle;"
                                    width="58.333333333333336%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 310px;"><img
                                                            alt="Screenshot Game 1"
                                                            height="auto"
                                                            src="https://d0d3920d1a.imgdist.com/pub/bfra/33gcmoa0/72g/dvv/nx7/308504-un-monton-de-monturas.jpg"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Screenshot Game 1" width="310"></div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-4" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-5" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #080808; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-6" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #080808; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: middle;"
                                    width="58.333333333333336%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 300px;"><img
                                                            alt="Screenshot game 2"
                                                            height="auto"
                                                            src="https://media.game.es/COVERV2/3D_L/176/176165.png"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Screenshot game 2" width="300"></div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-2"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: middle;"
                                    width="41.666666666666664%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="heading_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:center;width:100%;">
                                                <h2 style="margin: 0; color: #ffffff; direction: ltr; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 30px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: left; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;">
                                                    <span class="tinyMce-placeholder"
                                                          style="word-break: break-word; color: #ff9200;"><span
                                                            style="word-break: break-word; color: #ffffff;">Últimas Noticias:</span> ¡No te pierdas nada!.</span>
                                                </h2>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:10px;">
                                                <div style="color:#ffffff;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:300;letter-spacing:0px;line-height:1.5;text-align:left;mso-line-height-alt:24px;">
                                                    <p style="margin: 0;">Descubre las novedades, eventos y sorpresas
                                                        que tenemos para ti.</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="button_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:25px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:left;">
                                                <div align="left" class="alignment"><a href="https://www.example.com"
                                                                                       style="color:#ffffff;text-decoration:none;"
                                                                                       target="_blank">
                                                    <!--[if mso]>
                                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                                 href="https://www.example.com"
                                                                 style="height:52px;width:115px;v-text-anchor:middle;"
                                                                 arcsize="0%" fillcolor="#ff821c">
                                                        <v:stroke dashstyle="Solid" weight="0px" color="#ff821c"/>
                                                        <w:anchorlock/>
                                                        <v:textbox inset="0px,0px,0px,0px">
                                                            <center dir="false"
                                                                    style="color:#ffffff;font-family:sans-serif;font-size:16px">
                                                    <![endif]--><span class="button"
                                                                      style="background-color: #ff821c; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 0px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 10px; padding-top: 10px; padding-left: 30px; padding-right: 30px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span
                                                        style="word-break: break-word; line-height: 32px;">NOTICIAS</span></span>
                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-7" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #080808; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-8" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-9" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: middle;"
                                    width="41.666666666666664%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="heading_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:center;width:100%;">
                                                <h2 style="margin: 0; color: #ffffff; direction: ltr; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 30px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: left; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;">
                                                    Pase de Batalla: <span
                                                        style="word-break: break-word; color: #ff9200;">Tu acceso a la gloria</span>
                                                </h2>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:10px;">
                                                <div style="color:#ffffff;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:300;letter-spacing:0px;line-height:1.5;text-align:left;mso-line-height-alt:24px;">
                                                    <p style="margin: 0;">Desbloquea recompensas épicas, monturas
                                                        exclusivas y sorpresas únicas. ¡El campo de batalla te
                                                        espera!</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="button_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:25px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:left;">
                                                <div align="left" class="alignment"><a href="https://www.example.com"
                                                                                       style="color:#ffffff;text-decoration:none;"
                                                                                       target="_blank">
                                                    <!--[if mso]>
                                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                                 href="https://www.example.com"
                                                                 style="height:52px;width:119px;v-text-anchor:middle;"
                                                                 arcsize="0%" fillcolor="#ff821c">
                                                        <v:stroke dashstyle="Solid" weight="0px" color="#ff821c"/>
                                                        <w:anchorlock/>
                                                        <v:textbox inset="0px,0px,0px,0px">
                                                            <center dir="false"
                                                                    style="color:#ffffff;font-family:sans-serif;font-size:16px">
                                                    <![endif]--><span class="button"
                                                                      style="background-color: #ff821c; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 0px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 10px; padding-top: 10px; padding-left: 30px; padding-right: 30px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span
                                                        style="word-break: break-word; line-height: 32px;">COMPRAR</span></span>
                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-2"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: middle;"
                                    width="58.333333333333336%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 264px;"><img
                                                            alt="Game Box"
                                                            height="auto"
                                                            src="https://d0d3920d1a.imgdist.com/pub/bfra/33gcmoa0/tq5/vtx/lta/world-of-warcraft-5-0-battlechest-Photoroom.png"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Game Box" width="264">
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-10" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1f1005; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-11" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #321501; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <div class="spacer_block block-1"
                                         style="height:20px;line-height:20px;font-size:1px;">&#8202;
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-12" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #321501; border-radius: 0; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:10px;width:100%;">
                                                <div align="center" class="alignment">
                                                    <div style="max-width: 90px;"><a href="https://www.example.com"
                                                                                     target="_blank"><img
                                                            alt="Your Logo"
                                                            height="auto"
                                                            src="https://d0d3920d1a.imgdist.com/pub/bfra/33gcmoa0/k4h/3bt/lud/1200px-WoW_icon.svg.png"
                                                            style="display: block; height: auto; border: 0; width: 100%;"
                                                            title="Your Logo" width="90"></a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:10px;">
                                                <div style="color:#ff821c;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.5;text-align:center;mso-line-height-alt:24px;">
                                                    <p style="margin: 0;"><span
                                                            style="word-break: break-word; color: #ffffff;">¡Verifica tu correo y desbloquea la aventura completa!</span>
                                                    </p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="button_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:25px;padding-left:20px;padding-right:20px;padding-top:10px;text-align:center;">
                                                <div align="center" class="alignment"><a href="https://www.example.com"
                                                                                         style="color:#ffffff;text-decoration:none;"
                                                                                         target="_blank">
                                                    <!--[if mso]>
                                                    <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                                                 xmlns:w="urn:schemas-microsoft-com:office:word"
                                                                 href="https://www.example.com"
                                                                 style="height:52px;width:182px;v-text-anchor:middle;"
                                                                 arcsize="0%" fillcolor="#ff821c">
                                                        <v:stroke dashstyle="Solid" weight="0px" color="#ff821c"/>
                                                        <w:anchorlock/>
                                                        <v:textbox inset="0px,0px,0px,0px">
                                                            <center dir="false"
                                                                    style="color:#ffffff;font-family:sans-serif;font-size:16px">
                                                    <![endif]--><span class="button"
                                                                      style="background-color: #ff821c; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 0px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: Oswald, Arial, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 10px; padding-top: 10px; padding-left: 30px; padding-right: 30px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span
                                                        style="word-break: break-word; line-height: 32px;">CONFIRMAR CORREO</span></span>
                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="10" cellspacing="0" class="divider_block block-4"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div align="center" class="alignment">
                                                    <table border="0" cellpadding="0" cellspacing="0"
                                                           role="presentation"
                                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                                           width="90%">
                                                        <tr>
                                                            <td class="divider_inner"
                                                                style="font-size: 1px; line-height: 1px; border-top: 1px solid #5d3717;">
                                                                <span style="word-break: break-word;">&#8202;</span>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="social_block block-5"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:10px;text-align:center;">
                                                <div align="center" class="alignment">
                                                    <table border="0" cellpadding="0" cellspacing="0"
                                                           class="social-table"
                                                           role="presentation"
                                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;"
                                                           width="144px">
                                                        <tr>
                                                            <td style="padding:0 2px 0 2px;"><a
                                                                    href="https://www.facebook.com/"
                                                                    target="_blank"><img
                                                                    alt="Facebook"
                                                                    height="auto"
                                                                    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/facebook@2x.png"
                                                                    style="display: block; height: auto; border: 0;"
                                                                    title="facebook"
                                                                    width="32"></a>
                                                            </td>
                                                            <td style="padding:0 2px 0 2px;"><a
                                                                    href="https://www.twitter.com/" target="_blank"><img
                                                                    alt="Twitter"
                                                                    height="auto"
                                                                    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/twitter@2x.png"
                                                                    style="display: block; height: auto; border: 0;"
                                                                    title="twitter"
                                                                    width="32"></a>
                                                            </td>
                                                            <td style="padding:0 2px 0 2px;"><a
                                                                    href="https://www.linkedin.com/"
                                                                    target="_blank"><img
                                                                    alt="Linkedin"
                                                                    height="auto"
                                                                    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/linkedin@2x.png"
                                                                    style="display: block; height: auto; border: 0;"
                                                                    title="linkedin"
                                                                    width="32"></a>
                                                            </td>
                                                            <td style="padding:0 2px 0 2px;"><a
                                                                    href="https://www.instagram.com/"
                                                                    target="_blank"><img
                                                                    alt="Instagram"
                                                                    height="auto"
                                                                    src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/instagram@2x.png"
                                                                    style="display: block; height: auto; border: 0;"
                                                                    title="instagram"
                                                                    width="32"></a>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-6"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:20px;padding-left:30px;padding-right:30px;padding-top:10px;">
                                                <div style="color:#ffffff;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:13px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:center;mso-line-height-alt:16px;">
                                                    <p style="margin: 0;"><a href="http://www.example.com"
                                                                             rel="noopener"
                                                                             style="text-decoration: none; color: #ffffff;"
                                                                             target="_blank">Unsuscribe</a></p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="paragraph_block block-7"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:10px;">
                                                <div style="color:#8e5221;direction:ltr;font-family:Oswald, Arial, Helvetica Neue, Helvetica, sans-serif;font-size:12px;font-weight:400;letter-spacing:0px;line-height:1.5;text-align:center;mso-line-height-alt:18px;">
                                                    <p style="margin: 0;">¡Tu mundo gamer, siempre online y listo para
                                                        la acción!</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-13" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 600px; margin: 0 auto;"
                               width="600">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="icons_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center; line-height: 0;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;">
                                                <!--[if vml]>
                                                <table align="center" cellpadding="0" cellspacing="0"
                                                       role="presentation"
                                                       style="display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                                <![endif]-->

                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table><!-- End -->
</body>

</html>